apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
    name: {{ .Values.imagePullSecrets }}
    namespace: {{ .Values.namespace }}
data:
{{ .Files.Get "gitlab-registry.yaml" | nindent 2}}
