apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.applicationName }}-secret
    namespace: {{ .Values.namespace }}
data:
{{- if eq .Values.environment "production" -}}
{{ .Files.Get "secret-prod.yaml" | nindent 2}}
{{- else if eq .Values.environment "development" -}}
{{ .Files.Get "secret-dev.yaml" | nindent 2}}
{{- else -}}
{{ .Files.Get "secret-stage.yaml" | nindent 2}}
{{- end -}}
